name: tugas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Paket tambahan untuk lokal dan date formatting
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1

  # Supabase
  supabase_flutter: ^2.10.3

  # Database & storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5

  # Maps & location
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1

  # QR & crypto
  qr_flutter: ^4.1.0
  crypto: ^3.0.6

  # HTTP requests
  http: ^1.2.1
 

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
